
server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/students_info
    username: root
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: redis-17373.c73.us-east-1-2.ec2.redns.redis-cloud.com
      port: 17373
      username: default
      password: dU5CoOlYWmKIpNQu3Ohnn5AmSbjbK5YK
      timeout: 5000
      lettuce:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 1
          max-wait: 1000


  jpa:
    hibernate:
      ddl-auto: update  # use 'create', 'validate', 'none', or 'update' as needed
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  devtools:
    restart:
      enabled: true


